#!/bin/sh -x

# To obtain the paup input file containing the character S
# The outgroup is not in the file nb_cas_control.txt. It must be 
# specified with the option --outgroup (or -g)
../../../../altree-add-S -i caco.paup -j nb_cas_control.txt \
  -o et_caco.paup -e 1 -t SNP -p 0.58 --outgroup H000

# To run paup
paup et_caco.paup

# To perform the localisation analysis on the 89 equiparsimonious trees
~/recherche/logiciel/alphy/altree -i test.res.log  \
-j nb_cas_control.txt  -t SNP -p paup  --tree-to-analyse 89 \
--s-site-number 13 --s-site-characters "0->1" \
--co-evo double -l -o caco.loc
