#!/bin/sh

set -e

VERSION=$(cat Makefile.PL | \
	sed -e '/VERSION/s/.*'"'"'\([0-9a-ZA-Z._-]\+\)'"'"'.*/\1/p;d')

FORCE=""

while [ $# != 0 ]; do
  case "$1" in
  --force)
    echo "--force enabled. Disabling sanity check..."
    FORCE=yes
    ;;
  --dry-run|-n)
    echo "--dry-run enabled. No real release will be done."
    DRYRUN="echo DRY-RUN: "
    ;;
  --)
    shift
    break
    ;;
  -*)
    echo "Unknown option $1"
    echo "Aborting"
    exit 1
    ;;
  *)
    break;
    ;;
  esac
  shift
done

echo "Creating version '$VERSION'"

set -x
[ -f Makefile ] || perl Makefile.PL
make Makefile || true
make realclean
make -C Documentation distclean
set +x

if [ "$(svn st)" != "" ]; then
   echo "************************************"
   echo "* Not all files are commited/cleaned"
   echo "* Please correct before creating a release"
   echo "* (use 'svn st' to look for problematic files"
   echo "************************************"
   if [ "$FORCE" ]; then
     echo "* !!! WARNING: --force enabled : type 'ENTER to continue'"
     echo "************************************"
     read a
   else
     exit 1
   fi
fi
  
perl Makefile.PL

if [ "$(make distcheck 2>&1 1>/dev/null | grep -v "^No such file: META.yml$")" != "" ]; then
   echo "************************************"
   echo "* Not all files are in MANIFEST (or removed from it)"
   echo "* Please correct before creating a release"
   echo "* (use 'make distcheck' to look for problematic files"
   echo "************************************"
   if [ "$FORCE" ]; then
     echo "* !!! WARNING: --force enabled : type 'ENTER to continue'"
     echo "************************************"
     read a
   else
     exit 1
   fi
fi
  
D=svn+ssh://labri/usr/labri/danjean/svnroot/claire/altree/tags/release-$VERSION
if svn ls "$D" > /dev/null; then
   echo "************************************"
   echo "* Tag for revision $VERSION already exists"
   echo "* Did you really increase the revision number in Makefile.PL ?"
   echo "************************************"
   if [ "$FORCE" ]; then
     echo "* !!! WARNING: skipping creation tag"
     echo "* !!! WARNING: --force enabled : type 'ENTER to continue'"
     echo "************************************"
     read a
     DO_TAG=false
   else
     exit 1
   fi
else
  DO_TAG=true
fi

make disttest
make dist

if [ "$DO_TAG" = true ]; then
  $DRYRUN svn copy -m "Release $VERSION" \
    svn+ssh://labri/usr/labri/danjean/svnroot/claire/altree/trunk \
    "$D"
fi

echo "************************************"
echo "* SUCCESS !"
echo "************************************"
echo "* Release created in altree-$VERSION.tar.gz"
echo "* You need to copy this file to the web site"
echo "* and tell Vince to update the debian package"
echo "************************************"



