#!/bin/sh -x

# To run Famhap:
~/FAMHAP/FAMHAP15/famhap15 fam19_0 trio.fmh dp P

# To obtain phylip/paml input files using altree-convert
../../../altree-convert -i trio.fmh \
 -j fam19_0_H1_HAPLOTYPES -p phylip -r famhap -t NUM \
 -c nb_cas_control.txt -o trio.phy
