#!/bin/sh -x

# To add the character S 
# p=102 case haplotypes/176 haplotypes
# The outgroup is not specified in the file nb_cas_control.txt. The 
# option --outgroup must then be used
../../../../altree-add-S -i caco.paup -j \
nb_cas_control.txt  -o et_caco.paup -e 1 -t SNP -p 0.58 \
--outgroup H000

# To run paup on the file containing the character S
paup et_caco.paup

# To perform the localisation test
# All 89 equiparsimonious trees are analysed
../../../../altree -i test.res.log  \
-j nb_cas_control.txt  -t SNP -p paup  --tree-to-analyse 89 \
--s-site-number 13 --s-site-characters "0->1" \
--co-evo double -l -o caco.loc
