#!/bin/sh -x

# to run paup
paup caco.paup

# to perform the association test.
# only one permutation is done: the corrected p_value doesn't mean 
# anything!

../../../altree -i test.res.log  -j nb_cas_control.txt -a -t SNP \
 --outgroup H000 -p paup -b -r 1  --tree-to-analyse 1 > 1_caco.asso
